FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cultural-Events

Cultural-Events is a REST API to allow end users to look for events under RU.

# Allowed HTTP requests: 
<pre>
PUT     : Update resource
POST    : Create resource
GET     : Get a resource or list of resources 
DELETE  : To delete a resource
</pre>
# Organizers [/organizers]

### List All Organizers [GET /organizers/]

+ Response 200 (application/json)

        [
            {
                "id": "ab21421521baca"
                "name": "John Doe",
                "email": "xyz@example.com",
                "phone": "01711111111"
                "underRU": false
            }
            
            {
                "id": "ff85221551daca"
                "name": "XXX Dept.",
                "email": "abc@example.com",
                "phone": "01922222222"
                "underRU": true
            }
        ]
        
### Create a New Organizer [POST /organizers/]

+ Request (application/json)

        {
            "name": "Richard Roe",
            "email": "richie@example.com",
            "phone": "01674174561",
            "underRU": false
        }
        
+ Response 201 (application/json)
        
        {
            "id": "baca23154abad"
            "name": "Richard Roe",
            "email": "richie@example.com",
            "phone": "01674174561",
            "underRU": false
        }
        
### List Organizer by id [GET /organizers/{id}]
Retrieve a single organizer by id
+ Parameters
    + id (required, HexString, `ab21421521baca` ... HexString `id`  of the organizer to perform action with

+ Response 200 (application/json)

        {
            "id": "ab21421521baca"
            "name": "John Doe",
            "email": "xyz@example.com",
            "phone": "01711111111"
            "underRU": false
        }
        
### Update an Organizer by ID [PUT /organizers/{id}]      
Update an organizer under the collection with given id
+ Parameters
    + id (required, HexString, `ab21421521baca` ... HexString `id`  of the organizer to perform action with

+ Request (application/json) 

        {
            "name": "Jane Doe",
            "email": "ksi@example.com",
            "phone": "01711111111"
            "underRU": ture
        }
        
+ Response 201 (application/json)

        {
            "id": "ab21421521baca",
            "name": "Jane Doe",
            "email": "ksi@example.com",
            "phone": "01711111111"
            "underRU": ture
        }
        
### Remove an Organizer [DELETE /{id}]
+ Parameters
    + id (required, HexString, `ab21421521baca` ... HexString `id`  of the organizer to perform action with
    
+ Response 204

### List one or many organizers by name [GET /organizers/{name}]
Retrieve one or many entries with the given name under the collection

+ Parameters
    + name (required, String, `John Doe` ... String `name`  of the organizer to perform action with

+ Response 200 (application/json)
        
        [
            {
                "id": "1"
                "name": "John Doe",
                "email": "xyz@example.com",
                "phone": "01711111111"
                "underRU": false
            }
        ]